name: Deploy frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check Environment
      run: echo ${{ vars.VITE_API_BASEURL }}
      
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
      env:
        VITE_API_BASEURL: ${{ vars.VITE_API_BASEURL }}

    - name: Deploy to production
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rlgoDzvc --delete"
        SOURCE: "frontend/dist/"
        REMOTE_HOST: ${{ vars.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        TARGET: ${{ vars.TARGET }}
